### ISSUE TITLE
android.permission.READ_EXTERNAL_STORAGE denied for package

### ISSUE THREAD

**Issue by bugrevealingbme** [sahkari/wallpaper_handler#1]
E/MethodChannel#wallpaper_handler(25526): java.lang.SecurityException: Permission android.permission.READ_EXTERNAL_STORAGE denied for package net.reverse.killer
E/MethodChannel#wallpaper_handler(25526): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/MethodChannel#wallpaper_handler(25526): 	at android.os.Parcel.createException(Parcel.java:3041)
E/MethodChannel#wallpaper_handler(25526): 	at android.os.Parcel.readException(Parcel.java:3024)
E/MethodChannel#wallpaper_handler(25526): 	at android.os.Parcel.readException(Parcel.java:2966)
E/MethodChannel#wallpaper_handler(25526): 	at android.app.IWallpaperManager$Stub$Proxy.getWallpaperWithFeature(IWallpaperManager.java:1011)
E/MethodChannel#wallpaper_handler(25526): 	at android.app.WallpaperManager.getWallpaperFile(WallpaperManager.java:1702)
E/MethodChannel#wallpaper_handler(25526): 	at android.app.WallpaperManager.getWallpaperFile(WallpaperManager.java:1673)

**Comment by sahkari** [comment]
@bugrevealingbme 

It looks like you are facing a **`SecurityException`** related to **`android.permission.READ_EXTERNAL_STORAGE`**.  

Are you running the example from the plugin, or are you integrating this plugin into your own app?  

If you are using this plugin in your app, ensure that you have added the necessary **read permissions** in your **AndroidManifest.xml** file:  

```xml
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

Additionally, if you are targeting **Android 13 (API 33) or higher**, you should use the new **`READ_MEDIA_IMAGES`** permission instead:  

```xml
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
```

Let me know if you need more details or assistance.
